import React, { useState } from 'react';
import { X, Play, Pause, RotateCcw, Copy, Check, Sparkles, Plus, Trash2, ArrowRight } from 'lucide-react';
import { ThemeMode } from '../types';

interface KeyframePoint {
  id: string;
  step: number; // 0 to 100
  translateX: number;
  translateY: number;
  rotate: number;
  scale: number;
  opacity: number;
  borderRadius: number;
  bgColor: string;
}

interface KeyframeStudioModalProps {
  isOpen: boolean;
  onClose: () => void;
  onInjectCss: (cssSnippet: string) => void;
  theme: ThemeMode;
}

export const KeyframeStudioModal: React.FC<KeyframeStudioModalProps> = ({
  isOpen,
  onClose,
  onInjectCss,
  theme
}) => {
  if (!isOpen) return null;

  const [animName, setAnimName] = useState('pulseFloat');
  const [duration, setDuration] = useState(2);
  const [timing, setTiming] = useState('ease-in-out');
  const [iteration, setIteration] = useState('infinite');
  const [isPlaying, setIsPlaying] = useState(true);
  const [copied, setCopied] = useState(false);

  const [keyframes, setKeyframes] = useState<KeyframePoint[]>([
    { id: '1', step: 0, translateX: 0, translateY: 0, rotate: 0, scale: 1, opacity: 1, borderRadius: 16, bgColor: '#3b82f6' },
    { id: '2', step: 50, translateX: 0, translateY: -24, rotate: 6, scale: 1.1, opacity: 0.9, borderRadius: 28, bgColor: '#8b5cf6' },
    { id: '3', step: 100, translateX: 0, translateY: 0, rotate: 0, scale: 1, opacity: 1, borderRadius: 16, bgColor: '#3b82f6' }
  ]);

  const [selectedPointId, setSelectedPointId] = useState<string>('2');
  const currentPoint = keyframes.find(k => k.id === selectedPointId) || keyframes[0];

  const updateCurrentPoint = (patch: Partial<KeyframePoint>) => {
    setKeyframes(prev => prev.map(k => k.id === currentPoint.id ? { ...k, ...patch } : k));
  };

  const addKeyframePoint = () => {
    const existingSteps = keyframes.map(k => k.step);
    let nextStep = 25;
    if (existingSteps.includes(25) && !existingSteps.includes(75)) nextStep = 75;
    else if (existingSteps.includes(25) && existingSteps.includes(75)) nextStep = 40;

    const newPoint: KeyframePoint = {
      id: 'kf-' + Date.now(),
      step: nextStep,
      translateX: currentPoint.translateX,
      translateY: currentPoint.translateY,
      rotate: currentPoint.rotate,
      scale: currentPoint.scale,
      opacity: currentPoint.opacity,
      borderRadius: currentPoint.borderRadius,
      bgColor: currentPoint.bgColor
    };
    const updated = [...keyframes, newPoint].sort((a, b) => a.step - b.step);
    setKeyframes(updated);
    setSelectedPointId(newPoint.id);
  };

  const removeKeyframePoint = (id: string) => {
    if (keyframes.length <= 2) return;
    const remaining = keyframes.filter(k => k.id !== id);
    setKeyframes(remaining);
    setSelectedPointId(remaining[0].id);
  };

  // Generate CSS code
  const sortedKeyframes = [...keyframes].sort((a, b) => a.step - b.step);
  const keyframeBlocks = sortedKeyframes.map(k => {
    return `  ${k.step}% {
    transform: translate(${k.translateX}px, ${k.translateY}px) rotate(${k.rotate}deg) scale(${k.scale});
    opacity: ${k.opacity};
    border-radius: ${k.borderRadius}px;
    background-color: ${k.bgColor};
  }`;
  }).join('\n');

  const generatedCss = `/* Generated by SUI CodePulse Keyframe Studio */
@keyframes ${animName} {
${keyframeBlocks}
}

.${animName} {
  animation: ${animName} ${duration}s ${timing} ${iteration};
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCss);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handleInject = () => {
    onInjectCss('\n\n' + generatedCss);
    onClose();
  };

  const isDark = theme === 'dark';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fadeIn">
      <div className={`relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-2xl shadow-2xl border overflow-hidden ${
        isDark ? 'bg-slate-900 border-slate-700 text-slate-100' : 'bg-white border-slate-200 text-slate-900'
      }`}>
        {/* Header */}
        <div className={`flex items-center justify-between px-6 py-4 border-b ${
          isDark ? 'border-slate-800 bg-slate-900/80' : 'border-slate-200 bg-slate-50/80'
        }`}>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-blue-500/10 text-blue-500">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-semibold tracking-tight">CSS Keyframe & Animation Timeline</h2>
              <p className="text-xs text-slate-400">Design smooth @keyframes animations visually and inject clean CSS</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: Preview & Timeline (7 cols) */}
          <div className="lg:col-span-7 flex flex-col gap-5">
            {/* Live Animation Stage */}
            <div className={`relative h-64 rounded-xl border flex flex-col items-center justify-center overflow-hidden ${
              isDark ? 'bg-slate-950/70 border-slate-800' : 'bg-slate-100/70 border-slate-200'
            }`}>
              <style>{generatedCss}</style>

              {/* Animated Object */}
              <div
                className={`w-28 h-28 shadow-xl flex items-center justify-center font-bold text-white text-xs select-none ${
                  isPlaying ? animName : ''
                }`}
                style={!isPlaying ? {
                  transform: `translate(${currentPoint.translateX}px, ${currentPoint.translateY}px) rotate(${currentPoint.rotate}deg) scale(${currentPoint.scale})`,
                  opacity: currentPoint.opacity,
                  borderRadius: `${currentPoint.borderRadius}px`,
                  backgroundColor: currentPoint.bgColor
                } : undefined}
              >
                Pulse Box
              </div>

              {/* Controls Overlay */}
              <div className="absolute bottom-3 left-3 right-3 flex items-center justify-between px-3 py-1.5 rounded-lg bg-black/40 backdrop-blur-md text-xs text-white">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setIsPlaying(!isPlaying)}
                    className="p-1.5 rounded-md hover:bg-white/20 transition-colors"
                    title={isPlaying ? 'Pause' : 'Play'}
                  >
                    {isPlaying ? <Pause className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />}
                  </button>
                  <span>{animName} ({duration}s {timing})</span>
                </div>
                <span className="text-white/60">Live CSS Preview</span>
              </div>
            </div>

            {/* Timeline Scrubber */}
            <div className={`p-4 rounded-xl border ${isDark ? 'bg-slate-800/50 border-slate-700' : 'bg-slate-50 border-slate-200'}`}>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Timeline Keyframes</span>
                <button
                  onClick={addKeyframePoint}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-lg bg-blue-600 hover:bg-blue-500 text-white transition-colors"
                >
                  <Plus className="w-3 h-3" /> Add Stop
                </button>
              </div>

              {/* Step Badges Track */}
              <div className="flex items-center gap-2 overflow-x-auto pb-2">
                {sortedKeyframes.map((k) => (
                  <button
                    key={k.id}
                    onClick={() => {
                      setSelectedPointId(k.id);
                      setIsPlaying(false);
                    }}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                      selectedPointId === k.id
                        ? 'bg-blue-600 text-white shadow-md'
                        : isDark
                        ? 'bg-slate-700/60 text-slate-300 hover:bg-slate-700'
                        : 'bg-white text-slate-700 hover:bg-slate-200 border border-slate-200'
                    }`}
                  >
                    <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: k.bgColor }} />
                    <span>{k.step}%</span>
                    {keyframes.length > 2 && (
                      <span
                        onClick={(e) => {
                          e.stopPropagation();
                          removeKeyframePoint(k.id);
                        }}
                        className="hover:text-red-300 ml-1"
                      >
                        <Trash2 className="w-3 h-3" />
                      </span>
                    )}
                  </button>
                ))}
              </div>
            </div>

            {/* Animation Settings Bar */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <label className="block text-slate-400 mb-1">Name</label>
                <input
                  type="text"
                  value={animName}
                  onChange={(e) => setAnimName(e.target.value.replace(/[^a-zA-Z0-9_-]/g, ''))}
                  className={`w-full px-2.5 py-1.5 rounded-lg border text-xs ${
                    isDark ? 'bg-slate-800 border-slate-700 text-slate-100' : 'bg-white border-slate-300 text-slate-800'
                  }`}
                />
              </div>
              <div>
                <label className="block text-slate-400 mb-1">Duration ({duration}s)</label>
                <input
                  type="range"
                  min="0.2"
                  max="6"
                  step="0.1"
                  value={duration}
                  onChange={(e) => setDuration(parseFloat(e.target.value))}
                  className="w-full accent-blue-500"
                />
              </div>
              <div>
                <label className="block text-slate-400 mb-1">Timing</label>
                <select
                  value={timing}
                  onChange={(e) => setTiming(e.target.value)}
                  className={`w-full px-2 py-1.5 rounded-lg border text-xs ${
                    isDark ? 'bg-slate-800 border-slate-700 text-slate-100' : 'bg-white border-slate-300 text-slate-800'
                  }`}
                >
                  <option value="ease">ease</option>
                  <option value="ease-in-out">ease-in-out</option>
                  <option value="ease-in">ease-in</option>
                  <option value="ease-out">ease-out</option>
                  <option value="linear">linear</option>
                  <option value="cubic-bezier(0.68, -0.55, 0.27, 1.55)">bounce</option>
                </select>
              </div>
              <div>
                <label className="block text-slate-400 mb-1">Iteration</label>
                <select
                  value={iteration}
                  onChange={(e) => setIteration(e.target.value)}
                  className={`w-full px-2 py-1.5 rounded-lg border text-xs ${
                    isDark ? 'bg-slate-800 border-slate-700 text-slate-100' : 'bg-white border-slate-300 text-slate-800'
                  }`}
                >
                  <option value="infinite">infinite</option>
                  <option value="1">1 time</option>
                  <option value="2">2 times</option>
                  <option value="3">3 times</option>
                </select>
              </div>
            </div>
          </div>

          {/* Right: Active Stop Visual Properties (5 cols) */}
          <div className={`lg:col-span-5 p-4 rounded-xl border flex flex-col gap-3.5 text-xs ${
            isDark ? 'bg-slate-800/40 border-slate-700' : 'bg-slate-50 border-slate-200'
          }`}>
            <div className="flex items-center justify-between pb-2 border-b border-slate-700/50">
              <span className="font-semibold text-slate-200">Properties at {currentPoint.step}%</span>
              <div className="flex items-center gap-1.5">
                <span className="text-slate-400">Step:</span>
                <input
                  type="number"
                  min="0"
                  max="100"
                  value={currentPoint.step}
                  onChange={(e) => updateCurrentPoint({ step: Math.min(100, Math.max(0, parseInt(e.target.value) || 0)) })}
                  className={`w-14 px-1.5 py-0.5 rounded border text-center font-mono ${
                    isDark ? 'bg-slate-900 border-slate-600 text-slate-100' : 'bg-white border-slate-300'
                  }`}
                />
                <span className="text-slate-400">%</span>
              </div>
            </div>

            {/* Translate Y */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Translate Y</span>
                <span className="font-mono">{currentPoint.translateY}px</span>
              </div>
              <input
                type="range"
                min="-80"
                max="80"
                value={currentPoint.translateY}
                onChange={(e) => updateCurrentPoint({ translateY: parseInt(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Translate X */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Translate X</span>
                <span className="font-mono">{currentPoint.translateX}px</span>
              </div>
              <input
                type="range"
                min="-80"
                max="80"
                value={currentPoint.translateX}
                onChange={(e) => updateCurrentPoint({ translateX: parseInt(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Scale */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Scale</span>
                <span className="font-mono">{currentPoint.scale}x</span>
              </div>
              <input
                type="range"
                min="0.2"
                max="2"
                step="0.05"
                value={currentPoint.scale}
                onChange={(e) => updateCurrentPoint({ scale: parseFloat(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Rotate */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Rotate</span>
                <span className="font-mono">{currentPoint.rotate}°</span>
              </div>
              <input
                type="range"
                min="-180"
                max="180"
                value={currentPoint.rotate}
                onChange={(e) => updateCurrentPoint({ rotate: parseInt(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Opacity */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Opacity</span>
                <span className="font-mono">{Math.round(currentPoint.opacity * 100)}%</span>
              </div>
              <input
                type="range"
                min="0"
                max="1"
                step="0.05"
                value={currentPoint.opacity}
                onChange={(e) => updateCurrentPoint({ opacity: parseFloat(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Border Radius */}
            <div>
              <div className="flex justify-between text-slate-400 mb-1">
                <span>Border Radius</span>
                <span className="font-mono">{currentPoint.borderRadius}px</span>
              </div>
              <input
                type="range"
                min="0"
                max="60"
                value={currentPoint.borderRadius}
                onChange={(e) => updateCurrentPoint({ borderRadius: parseInt(e.target.value) })}
                className="w-full accent-blue-500"
              />
            </div>

            {/* Color */}
            <div className="flex items-center justify-between">
              <span className="text-slate-400">Background Color</span>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={currentPoint.bgColor}
                  onChange={(e) => updateCurrentPoint({ bgColor: e.target.value })}
                  className="w-8 h-8 rounded border-0 cursor-pointer p-0 bg-transparent"
                />
                <span className="font-mono text-xs text-slate-300">{currentPoint.bgColor}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className={`flex items-center justify-between px-6 py-4 border-t ${
          isDark ? 'border-slate-800 bg-slate-900/90' : 'border-slate-200 bg-slate-50/90'
        }`}>
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <span>Generated @keyframes {animName}</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium border transition-colors ${
                isDark ? 'border-slate-700 hover:bg-slate-800 text-slate-300' : 'border-slate-300 hover:bg-slate-100 text-slate-700'
              }`}
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy CSS'}</span>
            </button>
            <button
              onClick={handleInject}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-medium bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/20 transition-all"
            >
              <span>Inject to Project CSS</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
